--------------------------------------------------------------------------------
CREATE TABLE DEPARTMENT(
  DEPT_NO VARCHAR2(10) PRIMARY KEY,
  DEPT_NAME VARCHAR2(30) NOT NULL
);
--------------------------------------------------------------------------------
CREATE TABLE DOCTOR(
  DOC_NO VARCHAR2(20) PRIMARY KEY,
  DOC_NAME VARCHAR2(20) NOT NULL,
  DOC_ROOM NUMBER NOT NULL,
  DEPT_NO VARCHAR2(10) NOT NULL-- FK
);
ALTER TABLE DOCTOR
ADD CONSTRAINT DOC_DEPT_FK FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENT(DEPT_NO);
--------------------------------------------------------------------------------
CREATE TABLE PATIENT(
  PAT_NO VARCHAR2(20) PRIMARY KEY,
  PAT_ID VARCHAR2(20) NOT NULL,
  PAT_PW VARCHAR2(20) NOT NULL,
  PAT_NAME VARCHAR2(10) NOT NULL,
  PAT_PHONE VARCHAR2(30) NOT NULL,
  PAT_SSN VARCHAR2(14) NOT NULL,
  PAT_EMAIL VARCHAR2(40), -- NOT NULL 뺐음
  PAT_ADDRESS VARCHAR2(255) NOT NULL
);
--------------------------------------------------------------------------------
CREATE TABLE APPOINTMENT(
  APP_NO VARCHAR2(20) PRIMARY KEY,
  APP_DATE DATE NOT NULL,
  APP_MEMO VARCHAR2(300) ,
  PAT_NO VARCHAR2(20) NOT NULL, -- FK
  APP_FIRST CHAR(1) NOT NULL,
  DOC_NO VARCHAR2(20) NOT NULL, -- FK
  DEPT_NO VARCHAR2(10) NOT NULL -- FK
);
ALTER TABLE APPOINTMENT
ADD CONSTRAINT APP_PAT_FK FOREIGN KEY (PAT_NO) REFERENCES PATIENT(PAT_NO);
ALTER TABLE APPOINTMENT
ADD CONSTRAINT APP_DOC_FK FOREIGN KEY (DOC_NO) REFERENCES DOC(DOC_NO);
ALTER TABLE APPOINTMENT
ADD CONSTRAINT APP_DEPT_FK FOREIGN KEY(DEPT_NO) REFERENCES DEPARTMENT(DEPT_NO);
--------------------------------------------------------------------------------
INSERT INTO DEPARTMENT VALUES('D01','내과');
INSERT INTO DEPARTMENT VALUES('D02','외과');
INSERT INTO DEPARTMENT VALUES('D03','산부인과');
INSERT INTO DEPARTMENT VALUES('D04','성형외과');
INSERT INTO DEPARTMENT VALUES('D05','안과');
INSERT INTO DEPARTMENT VALUES('D06','정형외과');
INSERT INTO DEPARTMENT VALUES('D07','피부과');
INSERT INTO DEPARTMENT VALUES('D08','흉부외과');
INSERT INTO DEPARTMENT VALUES('D09','이비인후과');
INSERT INTO DEPARTMENT VALUES('D10','정신건강의학과');
--------------------------------------------------------------------------------
-- 의사 50
CREATE SEQUENCE DOC_SEQ -- DOC_NO SUQUENCE
START WITH 1
NOCYCLE
NOCACHE;

CREATE SEQUENCE DOC_R1_SEQ -- DOC_ROOM 내과 SEQUENCE
START WITH 101 MAXVALUE 199 NOCYCLE NOCACHE;
CREATE SEQUENCE DOC_R2_SEQ -- DOC_ROOM 외과 SEQUENCE
START WITH 201 MAXVALUE 299 NOCYCLE NOCACHE;
CREATE SEQUENCE DOC_R3_SEQ -- DOC_ROOM 산부인과 SEQUENCE
START WITH 301 MAXVALUE 399 NOCYCLE NOCACHE;
CREATE SEQUENCE DOC_R4_SEQ -- DOC_ROOM 성형외과 SEQUENCE
START WITH 401 MAXVALUE 499 NOCYCLE NOCACHE;
CREATE SEQUENCE DOC_R5_SEQ -- DOC_ROOM 안과 SEQUENCE
START WITH 501 MAXVALUE 599 NOCYCLE NOCACHE;
CREATE SEQUENCE DOC_R6_SEQ -- DOC_ROOM 정형외과 SEQUENCE
START WITH 601 MAXVALUE 699 NOCYCLE NOCACHE;
CREATE SEQUENCE DOC_R7_SEQ -- DOC_ROOM 피부과 SEQUENCE
START WITH 701 MAXVALUE 799 NOCYCLE NOCACHE;
CREATE SEQUENCE DOC_R8_SEQ -- DOC_ROOM 흉부외과 SEQUENCE
START WITH 801 MAXVALUE 899 NOCYCLE NOCACHE;
CREATE SEQUENCE DOC_R9_SEQ -- DOC_ROOM 이비인후과 SEQUENCE
START WITH 901 MAXVALUE 999 NOCYCLE NOCACHE;
CREATE SEQUENCE DOC_R10_SEQ -- DOC_ROOM 정신건강의학과 SEQUENCE
START WITH 1001 MAXVALUE 1099 NOCYCLE NOCACHE;

INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '한선기', DOC_R1_SEQ.NEXTVAL, 'D01');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '강중훈', DOC_R1_SEQ.NEXTVAL, 'D01');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '최만식', DOC_R1_SEQ.NEXTVAL, 'D01');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '정도연', DOC_R1_SEQ.NEXTVAL, 'D01');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '안석규', DOC_R1_SEQ.NEXTVAL, 'D01');

INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '성해교', DOC_R2_SEQ.NEXTVAL, 'D02');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '전우성', DOC_R2_SEQ.NEXTVAL, 'D02');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '엄정하', DOC_R2_SEQ.NEXTVAL, 'D02');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '심하균', DOC_R2_SEQ.NEXTVAL, 'D02');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '고승우', DOC_R2_SEQ.NEXTVAL, 'D02');

INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '이중기', DOC_R3_SEQ.NEXTVAL, 'D03');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '감우섭', DOC_R3_SEQ.NEXTVAL, 'D03');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '이태정', DOC_R3_SEQ.NEXTVAL, 'D03');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '안선기', DOC_R3_SEQ.NEXTVAL, 'D03');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '김민종', DOC_R3_SEQ.NEXTVAL, 'D03');

INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '유재석', DOC_R4_SEQ.NEXTVAL, 'D04');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '김은영', DOC_R4_SEQ.NEXTVAL, 'D04');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '윤성애', DOC_R4_SEQ.NEXTVAL, 'D04');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '신지원', DOC_R4_SEQ.NEXTVAL, 'D04');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '유정화', DOC_R4_SEQ.NEXTVAL, 'D04');

INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '이서연', DOC_R5_SEQ.NEXTVAL, 'D05');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '은상연', DOC_R5_SEQ.NEXTVAL, 'D05');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '안상건', DOC_R5_SEQ.NEXTVAL, 'D05');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '김성룡', DOC_R5_SEQ.NEXTVAL, 'D05');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '이종진', DOC_R5_SEQ.NEXTVAL, 'D05');

INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '송성묵', DOC_R6_SEQ.NEXTVAL, 'D06');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '박영선', DOC_R6_SEQ.NEXTVAL, 'D06');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '김진서', DOC_R6_SEQ.NEXTVAL, 'D06');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '박민준', DOC_R6_SEQ.NEXTVAL, 'D06');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '박정훈', DOC_R6_SEQ.NEXTVAL, 'D06');

INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '최윤선', DOC_R7_SEQ.NEXTVAL, 'D07');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '홍유정', DOC_R7_SEQ.NEXTVAL, 'D07');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '이하은', DOC_R7_SEQ.NEXTVAL, 'D07');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '박원우', DOC_R7_SEQ.NEXTVAL, 'D07');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '이준서', DOC_R7_SEQ.NEXTVAL, 'D07');

INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '유선화', DOC_R8_SEQ.NEXTVAL, 'D08');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '정동수', DOC_R8_SEQ.NEXTVAL, 'D08');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '주원호', DOC_R8_SEQ.NEXTVAL, 'D08');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '이영숙', DOC_R8_SEQ.NEXTVAL, 'D08');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '김혜진', DOC_R8_SEQ.NEXTVAL, 'D08');

INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '김영우', DOC_R9_SEQ.NEXTVAL, 'D09');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '공지후', DOC_R9_SEQ.NEXTVAL, 'D09');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '박정웅', DOC_R9_SEQ.NEXTVAL, 'D09');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '김정필', DOC_R9_SEQ.NEXTVAL, 'D09');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '박지예', DOC_R9_SEQ.NEXTVAL, 'D09');

INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '박민기', DOC_R10_SEQ.NEXTVAL, 'D10');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '양성철', DOC_R10_SEQ.NEXTVAL, 'D10');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '박종후', DOC_R10_SEQ.NEXTVAL, 'D10');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '김종수', DOC_R10_SEQ.NEXTVAL, 'D10');
INSERT INTO DOCTOR VALUES('D'||DOC_SEQ.NEXTVAL, '심민기', DOC_R10_SEQ.NEXTVAL, 'D10');
--------------------------------------------------------------------------------
-- 환자 100
CREATE SEQUENCE PAT_SEQ -- PAT_NO SUQUENCE
START WITH 1
NOCYCLE
NOCACHE;

INSERT INTO PATIENT VALUES ('P'||PAT_SEQ.NEXXTVAL, 'jjh1421', 'jhjh1212', '조재형', 
    '010-2314-1121', '720114-1724266', 'jjh@mms.com', '서울시 강남구 역삼동');



--------------------------------------------------------------------------------
-- 진료 120
